### PR TITLE
podman: test systemd socket activation, perf: cleanup, sysstat:cleanup

### PR DESCRIPTION
**Pull request by carlosrodfern**

### CODE REVIEW

**Comment by carlosrodfern** [comment]
I tested it in centos stream 8, but it hangs in centos stream 9.

You may not want to merge it until this issue I opened is resolved: https://bugzilla.redhat.com/show_bug.cgi?id=2231983
I can come back to post when it is fixed, and I rerun the test to verify the fix.

**Comment by carlosrodfern** [comment]
systemd 252-17 is available in centos stream 9. I tested it and it passes. This PR is ready now.

**Comment by AdamSaleh** [comment]
@carlosrodfern hi, I have noticed we had some problems with the github-actions based test-runner recently, I will look into this and hopefully merge it by tomorrow :)

**Comment by carlosrodfern** [comment]
@AdamSaleh , 
My last commit was the removal of the pydantic version pinning, since it is no longer necessary. However, I see there are conflicts. I removed that last commit and I'll bring it after this PR is merged, and I sync my fork.
Thank you.

**Comment by AdamSaleh** [comment]
Yeah, took me a bit, as I didn’t trust the gh action and checked this against a Duffy machines manually, both 8 and 9 stream. It works.

**Pull request merged**
