### PR TITLE
Test for valac: Compile and run a HelloWorld program

### PR DESCRIPTION
**Pull request by 843723683**
Test for valac: Compile and run a HelloWorld program

### CODE REVIEW

**Comment by arrfab** [comment]
Hi,
Thanks a lot for this PR. Had just a quick look, but it should then be modified to only cover the CentOS versions for which vala is available : we've modified recently all t_functional tests to work for CentOS 8, which is built and now automatically tested, but vala isn't available on el8.
Would you mind adapting your test to only be ran on specific centos releases? 
As a reminder, the same t_functional stack is used to validate centos 6, 7 and now 8.
Thanks :)

**Comment by 843723683** [comment]
Hi,
Thanks a lot for this message. I will modify my PR now according to your requirement and update again. Please check the PR again later. 
Thank you.

**Comment by 843723683** [comment]
Hello, I have just modified my PR according to your requirement and uploaded the revised PR. Please check.
Thank you.

**Comment by arrfab** [comment]
Thanks, but it would still fail for "t_InstallPackage vala" and so would fail on centos 6 and centos 8.
And for the other test, it would fail on centos 6 too

**Comment by 843723683** [comment]
Oh sorry.I will test on centos6 and resubmit. Where can I test the centos8?

**Comment by arrfab** [comment]
Either you can test on a rhel8, if you have the free developer subscription, or later on centos 8 when it will be publicly available : it's actually built and we have daily iterations that we test with up2date t_functional stack. Usually we also freeze t_functional tests during new releases, but can give it a try once you have something that looks good

**Comment by 843723683** [comment]
Hi, I have tested this version in CentOS6&7. But due to the lack of CentOS8, I have not tested in CentOS8. Please check again.
Thanks a lot.

**Comment by 843723683** [comment]
I used the shell to write an automated test framework that adds automated test scripts. A system performance test module has been added. Including: unixbench, stream, kernbench...
If you are interested, you can view it (https://github.com/843723683/Automation-Test-Framework). Download and test.
Do you have a platform for communication? I want to contribute my strength to the Centos project.what should I do?

**Comment by 843723683** [comment]
Hi,
I used the shell to write an automated test framework that adds automated test scripts. A system performance test module has been added. Including: unixbench, stream, kernbench...
If you are interested, you can view it (https://github.com/843723683/Automation-Test-Framework). Download and test.
Do you have a platform for communication? I want to contribute my strength to the Centos project.what should I do?
Thanks a lot.

**Pull request merged**
