### PR TITLE
Add tests for verifying that annobin is working properly with gcc

### PR DESCRIPTION
**Pull request by Conan-Kudo**

### CODE REVIEW

**Comment by carlwgeorge** [comment]
Thanks for the PR @Conan-Kudo!  Since annobin isn't in CentOS 7, can you wrap these in a conditional for CentOS 8 like here:

https://github.com/CentOS/sig-core-t_functional/blob/master/tests/z_rpminfo/check-rpminfo.sh#L5

**Comment by Conan-Kudo** [comment]
@carlwgeorge Done, thanks!

**Comment by arrfab** [comment]
LGTM , thanks .. merging !

**Comment by arrfab** [comment]
It seems it doesn't work though : https://ci.centos.org/view/CentOS-Core-QA/job/CentOS-Core-QA-t_functional-c8-stream-64/81/console

"[+] Fri 17 Apr 17:24:30 BST 2020 -> Running ./tests/p_annobin/10-test_annobin-gcc.sh - build a hello world program with gcc using annobin
gcc: error: -E or -x required when input is from standard input
./tests/p_annobin/10-test_annobin-gcc.sh: line 23: /tmp/tmp.GHrjST9s2y: Permission denied"

**Comment by Conan-Kudo** [comment]
Blech, let me fix that...

**Comment by Conan-Kudo** [comment]
Submitted as #53

**Pull request merged**
